task_app/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :statuses
end

task_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

task_app/app/models/status.rb
class Status < ApplicationRecord
    validates :name, presence: true, length: {minimum: 1}
end

task_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

task_app/app/controllers/statuses_controller.rb
# frozen_string_literal: true

class StatusesController < ApplicationController
  def new
    @status = Status.new
  end
  # end def new

  def index
    @statuses = Status.all
    # @statuses = @statuses.sort_by(&:name)
  end
  # end def index

  def show
    @status = Status.find(params[:id])
  end
  # end def show

  def edit
    @status = Status.find(params[:id])
  end
  # end def edit

  def create
    @status = Status.new(params.require(:status).permit(:name, :isActive))
    puts @status
    if @status.save
      redirect_to statuses_path
    else
      render 'new'
    end
    # end if-else
  end
  # end def create

  def update
    @status = Status.find(params[:id])
    if @status.update(params.require(:status).permit(:name, :isActive))
      redirect_to statuses_path
    else
      render 'edit'
    end
    # end if-else
  end
  # end def update

  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    redirect_to statuses_path
  end
  # end def destroy
end
# end class

task_app/app/helpers/application_helper.rb
module ApplicationHelper
end

task_app/app/helpers/statuses_helper.rb
module StatusesHelper
end

task_app/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

task_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container-fluid">
      <%= render 'layouts/navigation' %>
      <%= yield %>
    </div>
  </body>
</html>

task_app/app/views/statuses/_statusHeader.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-secondary" role="alert">
            <h3>Status</h3>
        </div>
    </div>
</div>

task_app/app/views/statuses/edit.html.erb
<%= render 'statusHeader' %>
<div class="row">
  <div class="col-md-4 col-sm-12 offset-md-4">
    <div class="card">
      <div class="card-header">
        Update Status [Name: <%= @status.name %>]
      </div>
      <div class="card-body">
        <%= form_with(model: @status, local: true) do |form| %>
          <div class="form-group row">
            <%= form.label :name, :class=> "col-sm-2 col-form-label" %> &nbsp;
            <div class="col-sm-9">
              <%= form.text_field :name, :class=> "form-control" %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-2">
              <%= form.label :Active?, :class=> "form-check-label"  %>
            </div>
            <div class="col-sm-9">
              <%= form.check_box :isActive, :class=>"form-check-input", :style=> "margin-top: 2%; margin-left: 1.5%" %>
            </div>
          </div>
          <% if @status.errors.any? %>
            <div class="alert alert-danger col-md-12" role="alert">
              <h6>
                <%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:
              </h6>
              <ul>
                <% @status.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <p class="text-center">
            <%= form.submit "Update", :class=> "btn btn-success" %>
          </p>
        <% end %>
        <div class="row">
          <%= link_to fa_icon('chevron-left', text: 'Go back to index'), statuses_path, :class=> "btn btn-link" %>
        </div>
      </div>
    </div>
  </div>
</div>

task_app/app/views/statuses/index.html.erb
<%= render 'statusHeader' %>
<div class="row">
  <div class="col-md-12">
    <%= link_to fa_icon('plus', text: "New Status"), new_status_path, class: "btn btn-primary" %>
  </div>
</div>
<!--end div class="row"-->
<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-sm table-striped table-hover">
        <tr class="table-dark text-center">
          <th>Sl.</th>
          <th>Name</th>
          <th>Is Active?</th>
          <th></th>
        </tr>
        <% if @statuses.empty? == false %>
          <% @statuses.sort_by(&:name).each_with_index do |status, i| %>
            <tr>
              <td class="text-center"><%= i + 1 %></td>
              <td><%= status.name %></td>
              <td class="text-center">
                <% if status.isActive? %>
                  <%= fa_icon('check', class: 'text-success')%>
                <% else %>
                  <%= fa_icon('times', class: 'text-danger')%>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to fa_icon('edit', text: 'Edit'), edit_status_path(status), :class=> "btn btn-sm btn-warning" %>
                <%= link_to fa_icon('trash', text: 'Delete'), status_path(status),
                                        method: :delete,
                                        data: { confirm: 'Are you sure you want delete?' },
                                        :class => "btn btn-sm btn-danger" %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan=4 class="text-center">
              No data found
            </td>
          </tr>
        <% end %>
        <!-- end if-else -->
      </table>
    </div>
  </div>
</div>
<!-- end div class="row"-->

task_app/app/views/statuses/new.html.erb
<%= render 'statusHeader' %>
<div class="row">
  <div class="col-md-4 col-sm-12 offset-md-4">
    <div class="card">
      <div class="card-header">
        Add New Status
      </div>
      <div class="card-body">
        <%= form_with scope: :status, url: statuses_path, local: true do |form| %>
          <div class="form-group row">
            <%= form.label :name, :class=> "col-sm-2 col-form-label" %> &nbsp;
            <div class="col-sm-9">
              <%= form.text_field :name, :class=> "form-control" %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-2">
              <%= form.label :Active?, :class=> "form-check-label"  %>
            </div>
            <div class="col-sm-9">
              <%= form.check_box :isActive, :class=>"form-check-input", :style=> "margin-top: 2%; margin-left: 1.5%" %>
            </div>
          </div>
          <% if @status.errors.any? %>
            <div class="alert alert-danger col-md-12" role="alert">
              <h6>
                <%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:
              </h6>
              <ul>
                <% @status.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <p class="text-center">
            <%= form.submit "Add", :class=> "btn btn-success" %>
          </p>
        <% end %>
        <div class="row">
          <%= link_to fa_icon('chevron-left', text: 'Go back to index'), statuses_path, :class=> "btn btn-link" %>
        </div>
      </div>
    </div>
  </div>
</div>